# Generated by Django 3.1.3 on 2020-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201121_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_main_page', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='datamain',
            name='views_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
